version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: undead_sheep
      MONGO_INITDB_ROOT_PASSWORD: foxtrot_uniform 
    volumes:
      - ./database_storage:/data/db
    ports:
      - 27017:27017
